name:                pta-exercises
version:             0.1.0.0
github:              "timeflieslikeanarrow/pta-exercises"
license:             BSD3
author:              "Jian Shi"
maintainer:          "timeflieslikeanarrow001@gmail.com"
copyright:           "Copyright: (c) 2021-2030 Jian Shi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timeflieslikeanarrow/pta-exercises#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  pta-exercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pta-exercises

tests:
  pta-exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pta-exercises
    - hspec
    - hspec-discover
    - hspec-expectations
    - QuickCheck